language: rust
rust:
  - nightly
cache: cargo
sudo: required
install:
  - ./build_utils/googletest.sh
  - ./build_utils/libhdfs3.sh
  - ./build_utils/kcov.sh

before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - cargo install cargo-kcov ||Â echo "Cargo kcov already installed"

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - rustdoc --test readme.md -L target

after_success:
  - cargo kcov --all --verbose --no-clean-rebuild

notifications:
  email:
    on_success: never
addons:
  apt:
    packages:
      - cmake
      - libssl-dev
      - libgtest-dev
      - libboost-dev
      - libxml2-dev
      - libkrb5-dev
      - libgsasl7-dev
      - uuid-dev
      - libprotobuf-dev
      - protobuf-compiler
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
    sources:
      - kalakris-cmake
